### PR TITLE
auction, oracle and prices brief documentation

### PR DESCRIPTION
**Pull request by ermalkaleci**

### CODE REVIEW

**Comment by ermalkaleci** [comment]
@shaopengw later we can do a proper documentation and publish to crates.io

**Comment by ermalkaleci** [comment]
@shaopengw or we can host the docs somewhere else

**Comment by shaopengw** [comment]
@ermalkaleci Yep, meanwhile we could keep an eye on how substrate pallets are handling documentations, since orml are similar to them. :]

**Comment by xlc** [comment]
I will try to keep the docs in README less technical, and leave the technical details in Rust file as docs comments.

**Comment by shaopengw** [comment]
@xlc I thought the requirements were to provide technical documentation like other pallet modules.

**Comment by shaopengw** [comment]
After discussing with @xlc , our documentation would be like:
- In the repo level of readme, add each module's simple introduction(one line or two).
- In each module, add a readme file covering module overview.
- In each module's `lib.rs`, add technical doc comments.

**Pull request merged**
